In [37]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [38]:
df= pd.read_csv('cars.csv')
df.sample(10)

           brand  km_driven    fuel         owner  selling_price
3089      Toyota      25538  Petrol   First Owner         625000
2189      Maruti      25000  Petrol   First Owner         400000
5931        Tata      20000  Petrol   First Owner         500000
7762  Volkswagen      36800  Diesel   First Owner         695000
661          BMW       8500  Diesel   First Owner        5500000
2695      Maruti      60000  Petrol  Second Owner         270000
6130        Tata      50000  Diesel   Third Owner         180000
3962        Ford      60000  Diesel   First Owner         700000
4201      Datsun       5000  Petrol  Second Owner         430000
5257        Land      21000  Diesel   First Owner        4500000

In [39]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [40]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [41]:
df['fuel'].nunique()

4

## One hot encoding using pandas
### Using the get_dummies() function

In [42]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## k-1 Encoding

In [43]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# using sklearn

In [44]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [45]:
x_train, x_test , y_train , y_test = train_test_split(df.drop('selling_price',axis=1),
                                                     df['selling_price'],
                                                     test_size=0.2)

In [46]:
x_test

         brand  km_driven    fuel         owner
7086    Toyota     120000  Petrol  Second Owner
8070     Honda      60000  Diesel   First Owner
1271  Mahindra     100000  Diesel   First Owner
517    Hyundai      38000  Petrol   First Owner
4415     Lexus      20000  Petrol   First Owner
...        ...        ...     ...           ...
7055  Mahindra      70000  Diesel   Third Owner
1647    Maruti     110000  Diesel   First Owner
7586    Maruti       5000  Petrol   First Owner
7345  Mahindra     114000  Diesel   First Owner
1391    Maruti      72000  Diesel   First Owner

[1626 rows x 4 columns]

### One hot encoder ka obj bana dia

In [49]:
ohe=OneHotEncoder(drop='first')

fitting and transforming ek hi line me

In [50]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [51]:
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()

In [52]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Tata', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 70000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Volkswagen', 155000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Mahindra', 79500, 1.0, ..., 0.0, 0.0, 0.0],
       ['Ford', 90000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Mahindra', 60000, 1.0, ..., 1.0, 0.0, 0.0]], dtype=object)

## now on brand column

This column has many categories

In [64]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [63]:
df['brand'].nunique()

32

In [60]:
threshold=100
repl=counts[counts<=threshold].index

In [61]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7832,False,False,False,False,True,False,False,False,False,False,False,False,False
3646,False,False,False,False,False,True,False,False,False,False,False,False,False
3656,False,False,False,False,False,False,False,False,False,False,False,True,False
3368,False,False,False,False,True,False,False,False,False,False,False,False,False
5634,False,False,False,False,False,False,True,False,False,False,False,False,False