In [5]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [8]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [9]:
df['fuel'].nunique()

4

## One hot encoding using pandas
### Using the get_dummies() function

In [10]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## k-1 Encoding

In [11]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# using sklearn

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test , y_train , y_test = train_test_split(df.drop('selling_price',axis=1),
                                                     df['selling_price'],
                                                     test_size=0.2)

In [14]:
x_test

        brand  km_driven    fuel         owner
7266     Tata      50000  Diesel  Second Owner
5007    Honda     130000  Petrol   First Owner
3176  Hyundai      39000  Diesel   First Owner
952    Maruti       5000  Petrol   First Owner
4642     Tata      50000  Diesel   First Owner
...       ...        ...     ...           ...
5814   Maruti      20000  Petrol   First Owner
1422   Maruti      90000  Diesel  Second Owner
5947    Honda      27233  Diesel   First Owner
6216     Tata     120000  Diesel   First Owner
5527   Maruti      25000  Petrol  Second Owner

[1626 rows x 4 columns]

### One hot encoder ka obj bana dia

In [15]:
ohe=OneHotEncoder(drop='first')

fitting and transforming ek hi line me

In [16]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [17]:
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()

In [18]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Jaguar', 45000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 19500, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 50000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Chevrolet', 136000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 110000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 46000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

## now on brand column

This column has many categories

In [19]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [20]:
df['brand'].nunique()

32

In [21]:
threshold=100
repl=counts[counts<=threshold].index

In [22]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5077,False,False,False,False,False,False,False,False,False,False,False,False,True
7957,False,False,False,True,False,False,False,False,False,False,False,False,False
294,False,False,False,False,True,False,False,False,False,False,False,False,False
6370,False,False,False,False,True,False,False,False,False,False,False,False,False
505,False,True,False,False,False,False,False,False,False,False,False,False,False