In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [7]:
df= pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df.sample(10)

          brand  km_driven    fuel         owner  selling_price
6405  Chevrolet      80000  Diesel   First Owner         490000
5926     Maruti      70000  Diesel   First Owner         600000
3922   Mahindra      47990  Diesel  Second Owner         210000
4097        Kia       5000  Diesel   First Owner        1900000
2140     Daewoo      46951  Petrol   First Owner          86000
2116     Maruti      80000  Petrol   First Owner         390000
7448  Chevrolet     120000  Petrol   First Owner         145000
2868     Maruti      28000  Petrol   First Owner         680000
6323     Maruti     121000  Petrol   First Owner         200000
1811     Maruti      70000  Petrol   Third Owner         170000

In [10]:
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [12]:
df_new=(df['km_driven'],df['selling_price'])

In [16]:
df_new
df_new=pd.DataFrame(df_new)

In [17]:
df_new

,0,1,2,3,4,5,6,7,8,9,...,8118,8119,8120,8121,8122,8123,8124,8125,8126,8127
km_driven,145500,120000,140000,127000,120000,45000,175000,5000,90000,169000,...,25000,80000,191000,50000,80000,110000,119000,120000,25000,25000
selling_price,450000,370000,158000,225000,130000,440000,96000,45000,350000,200000,...,380000,360000,120000,260000,475000,320000,135000,382000,290000,290000

In [20]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, km_driven to selling_price
Columns: 8128 entries, 0 to 8127
dtypes: int64(8128)
memory usage: 127.0+ KB