In [543]:
import pandas as pd
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [544]:
df = pd.read_csv('Titanic-Dataset.csv')
df.sample(5)

     PassengerId  Survived  Pclass  ...      Fare Cabin  Embarked
778          779         0       3  ...    7.7375   NaN         Q
262          263         0       1  ...   79.6500   E67         S
449          450         1       1  ...   30.5000  C104         S
824          825         0       3  ...   39.6875   NaN         S
730          731         1       1  ...  211.3375    B5         S

[5 rows x 12 columns]

In [545]:
df= df.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [546]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [547]:
x_train,x_test, y_train , y_test = train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size=0.3,random_state=42)

In [548]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
445       1    male   4.0      0      2   81.8583        S
650       3    male   NaN      0      0    7.8958        S
172       3  female   1.0      1      1   11.1333        S
450       2    male  36.0      1      2   27.7500        S
314       2    male  43.0      1      1   26.2500        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[623 rows x 7 columns]

In [549]:
x_test

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709       3    male   NaN      1      1  15.2458        C
439       2    male  31.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
720       2  female   6.0      0      1  33.0000        S
39        3  female  14.0      1      0  11.2417        C
..      ...     ...   ...    ...    ...      ...      ...
821       3    male  27.0      0      0   8.6625        S
633       1    male   NaN      0      0   0.0000        S
456       1    male  65.0      0      0  26.5500        S
500       3    male  17.0      0      0   8.6625        S
430       1    male  28.0      0      0  26.5500        S

[268 rows x 7 columns]

In [550]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [551]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [552]:
x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked_imputed = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked_imputed = si_embarked.transform(x_test[['Embarked']])

In [553]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [554]:
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
# One-hot encoding
x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked_imputed)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked_imputed)

In [555]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [556]:

x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
445       1    male   4.0      0      2  81.8583        S
650       3    male   NaN      0      0   7.8958        S
172       3  female   1.0      1      1  11.1333        S
450       2    male  36.0      1      2  27.7500        S
314       2    male  43.0      1      1  26.2500        S

In [557]:
x_train_rem = x_train.drop(columns=['Sex','Age','Embarked'])

In [558]:
x_test_rem = x_test.drop(columns=['Sex','Age','Embarked'])

In [559]:
x_train_transformed = np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)
x_test_transformed = np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_embarked),axis=1)

In [560]:
x_test_transformed.shape

(268, 10)

In [561]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [562]:
y_pred = clf.predict(x_test_transformed)
y_pred

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0])

In [563]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.746268656716418

In [564]:

import pickle

In [567]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))