### Implementing Logistic Regression using a single perceptron and comparing it with scikit learn's implementation on a toy dataset

In [158]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_regression 
from sklearn.metrics import accuracy_score , precision_score , recall_score,f1_score

In [ ]:
df = pd.read_csv('placement.csv')

In [ ]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [ ]:
df=df.drop(columns=['Unnamed: 0'])

In [ ]:
df.describe()

             cgpa          iq   placement
count  100.000000  100.000000  100.000000
mean     5.991000  123.580000    0.500000
std      1.143634   39.944198    0.502519
min      3.300000   37.000000    0.000000
25%      5.075000  101.500000    0.000000
50%      6.000000  127.500000    0.500000
75%      6.900000  149.000000    1.000000
max      8.500000  233.000000    1.000000

In [ ]:
type(df)

pandas.core.frame.DataFrame